"""empty message

Revision ID: 1555f1a5766f
Revises: ce485722fb52
Create Date: 2025-06-06 20:40:50.086920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1555f1a5766f'
down_revision: Union[str, None] = 'ce485722fb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('transcription', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'transcription')
    # ### end Alembic commands ###
