"""empty message

Revision ID: c2c74bbd9f05
Revises: 1555f1a5766f
Create Date: 2025-07-17 08:19:24.972304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c74bbd9f05'
down_revision: Union[str, None] = '1555f1a5766f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('words', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('words', 'transcription',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'transcription',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('words', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
